### ISSUE TITLE
关于mac上报错的问题

### ISSUE THREAD

**Issue by GJZ0117** [v2rayA/homebrew-v2raya#2] opened 2023-12-26 15:47 UTC
在MacBook pro m2 pro 系统版本13.4上通过homebrew安装了v2raya，通过浏览器配置订阅的节点后，可以正常使用代理服务，但在启动时和更新时候会报错  failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org: no such host

详细日志：
2023/12/26 15:37:43.075 [E] [version.go:39] failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org: no such host
2023/12/26 15:37:57.435 [E] [connection.go:88] failed to start v2ray-core: failed: no server is selected. please select at least one server
2023/12/26 15:38:05.749 [I] [io.go:432] V2Ray 5.8.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.10 darwin/arm64)
2023/12/26 15:38:05.749 [I] [io.go:432] A unified platform for anti-censorship.
2023/12/26 15:38:07.173 [I] [io.go:432] 127.0.0.1:56209 accepted tcp:127.0.0.1:0 [api-out]
2023/12/26 15:38:07.705 [I] [io.go:432] 127.0.0.1:56211 accepted tcp:127.0.0.1:0 [api-out]

虽然目前不影响使用，但还是希望能改好。请问这种情况需要如何处理？

**Comment by MarksonHon** [comment] 2024-02-26 09:47
not a bug about homebrew tap and fixed by upstream

**Closed as completed by MarksonHon** 2024-02-26 09:47 UTC
